ConsoleColor color = Console.ForegroundColor;
Console.ForegroundColor = ConsoleColor.DarkGreen;
Console.Clear();
Console.WriteLine("Ejemplo de cadena de texto");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Presione una tecla para continuar...");
Console.ReadKey();
Console.Clear();
Console.WriteLine("Ingrese un caracter: ");
char caracter = char.Parse(Console.ReadLine());
Console.WriteLine($"Caracter ingresado: {caracter}");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Conversión a codigo ASCII");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine($"El código ASCII del caracter {caracter} es: {(int)caracter}");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Presione una tecla para continuar...");
Console.ReadKey();
Console.Clear();
Console.WriteLine("Concatenación de cadenas de texto");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Presione una tecla para continuar...");
Console.ReadKey();
Console.Clear();
Console.WriteLine("Ingrese una cadena de texto: ");
string cadena1 = Console.ReadLine();
Console.WriteLine($"Cadena ingresada: {cadena1}");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Ingrese otra cadena de texto: ");
string cadena2 = Console.ReadLine();
Console.WriteLine($"Cadena ingresada: {cadena2}");
Console.WriteLine("-----------------------------------------------------------");
string cadenaConcatenada = cadena1 + " " + cadena2;
Console.WriteLine("Cadenas concatenadas: " + cadenaConcatenada);
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Presione una tecla para continuar...");
Console.ReadKey();
Console.Clear();
Console.WriteLine("Comparación de cadenas de texto");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Presione una tecla para continuar...");
Console.ReadKey();
Console.Clear();
Console.WriteLine("Ingrese una cadena de texto: ");
string cadena3 = Console.ReadLine();
Console.WriteLine($"Cadena ingresada: {cadena3}");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Ingrese otra cadena de texto: ");
string cadena4 = Console.ReadLine();
Console.WriteLine($"Cadena ingresada: {cadena4}");
Console.WriteLine("-----------------------------------------------------------");
if (cadena3 == cadena4)
{
    Console.WriteLine("Las cadenas son iguales");
}
else
{
    Console.WriteLine("Las cadenas son diferentes");
}
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Presione una tecla para continuar...");
Console.ReadKey();
Console.Clear();
Console.WriteLine("Comparación de cadenas de texto (ignorando mayúsculas y minúsculas)");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Presione una tecla para continuar...");
Console.ReadKey();
Console.Clear();
Console.WriteLine("Ingrese una cadena de texto: ");
string cadena5 = Console.ReadLine();
Console.WriteLine($"Cadena ingresada: {cadena5}");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Ingrese otra cadena de texto: ");
string cadena6 = Console.ReadLine();
Console.WriteLine($"Cadena ingresada: {cadena6}");
Console.WriteLine("-----------------------------------------------------------");
if (cadena5.ToLower() == cadena6.ToLower())
{
    Console.WriteLine("Las cadenas son iguales");
}
else
{
    Console.WriteLine("Las cadenas son diferentes");
}
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Presione una tecla para continuar...");
Console.ReadKey();
Console.Clear();
Console.WriteLine("Longitud de una cadena de texto");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Presione una tecla para continuar...");
Console.ReadKey();
Console.Clear();
Console.WriteLine("Ingrese una cadena de texto: ");
string cadena7 = Console.ReadLine();
Console.WriteLine($"Cadena ingresada: {cadena7}");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine($"La longitud de la cadena es: {cadena7.Length}");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Presione una tecla para continuar...");
Console.ReadKey();
Console.Clear();
Console.WriteLine("Extracción de subcadenas");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Presione una tecla para continuar...");
Console.ReadKey();
Console.Clear();
Console.WriteLine("Ingrese una cadena de texto: ");
string cadena8 = Console.ReadLine();
Console.WriteLine($"Cadena ingresada: {cadena8}");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Ingrese la posición inicial: ");
int posicionInicial = int.Parse(Console.ReadLine());
Console.WriteLine("Ingrese la longitud de la subcadena: ");
int longitud = int.Parse(Console.ReadLine());
Console.WriteLine("-----------------------------------------------------------");
string subcadena = cadena8.Substring(posicionInicial, longitud);
Console.WriteLine($"La subcadena es: {subcadena}");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Presione una tecla para continuar...");
Console.ReadKey();
Console.Clear();
Console.WriteLine("Búsqueda de subcadenas");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Presione una tecla para continuar...");
Console.ReadKey();
Console.Clear();
Console.WriteLine("Ingrese una cadena de texto: ");
string cadena9 = Console.ReadLine();
Console.WriteLine($"Cadena ingresada: {cadena9}");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Ingrese la subcadena a buscar: ");
string subcadenaABuscar = Console.ReadLine();
Console.WriteLine("-----------------------------------------------------------");
if (cadena9.Contains(subcadenaABuscar))
{
    Console.WriteLine("La subcadena se encuentra en la cadena");
}
else
{
    Console.WriteLine("La subcadena no se encuentra en la cadena");
}
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Presione una tecla para continuar...");
Console.ReadKey();
Console.Clear();
Console.WriteLine("Reemplazo de subcadenas");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Presione una tecla para continuar...");
Console.ReadKey();
Console.Clear();
Console.WriteLine("Ingrese una cadena de texto: ");
string cadena10 = Console.ReadLine();
Console.WriteLine($"Cadena ingresada: {cadena10}");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Ingrese la subcadena a reemplazar: ");
string subcadenaAReemplazar = Console.ReadLine();
Console.WriteLine("Ingrese la subcadena de reemplazo: ");
string subcadenaDeReemplazo = Console.ReadLine();
Console.WriteLine("-----------------------------------------------------------");
string cadenaReemplazada = cadena10.Replace(subcadenaAReemplazar, subcadenaDeReemplazo);
Console.WriteLine($"La cadena reemplazada es: {cadenaReemplazada}");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Presione una tecla para continuar...");
Console.ReadKey();
Console.Clear();
Console.WriteLine("División de cadenas de texto");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Presione una tecla para continuar...");
Console.ReadKey();
Console.Clear();
Console.WriteLine("Ingrese una cadena de texto: ");
string cadena11 = Console.ReadLine();
Console.WriteLine($"Cadena ingresada: {cadena11}");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Ingrese el separador: ");
char separador = char.Parse(Console.ReadLine());
Console.WriteLine("-----------------------------------------------------------");
string[] subcadenas = cadena11.Split(separador);
Console.WriteLine("Subcadenas:");
foreach (string subcadenaActual in subcadenas)
{
    Console.WriteLine(subcadenaActual);
}
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Presione una tecla para continuar...");
Console.ReadKey();
Console.Clear();
Console.WriteLine("Eliminación de espacios en blanco");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Presione una tecla para continuar...");
Console.ReadKey();
Console.Clear();
Console.WriteLine("Ingrese una cadena de texto: ");
string cadena12 = Console.ReadLine();
Console.WriteLine($"Cadena ingresada: {cadena12}");
Console.WriteLine("-----------------------------------------------------------");
string cadenaSinEspacios = cadena12.Trim();
Console.WriteLine($"La cadena sin espacios es: {cadenaSinEspacios}");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Presione una tecla para continuar...");
Console.ReadKey();
Console.Clear();
Console.WriteLine("Convertir a mayúsculas y minúsculas");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Presione una tecla para continuar...");
Console.ReadKey();
Console.Clear();
Console.WriteLine("Ingrese una cadena de texto: ");
string cadena13 = Console.ReadLine();
Console.WriteLine($"Cadena ingresada: {cadena13}");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Cadena en mayúsculas: " + cadena13.ToUpper());
Console.WriteLine("Cadena en minúsculas: " + cadena13.ToLower());
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Presione una tecla para continuar...");
Console.ReadKey();
Console.Clear();
Console.WriteLine("Inserción de cadenas de texto");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Presione una tecla para continuar...");
Console.ReadKey();
Console.Clear();
Console.WriteLine("Ingrese una cadena de texto: ");
string cadena14 = Console.ReadLine();
Console.WriteLine($"Cadena ingresada: {cadena14}");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Ingrese la posición de inserción: ");
int posicionInsercion = int.Parse(Console.ReadLine());
Console.WriteLine("Ingrese la cadena a insertar: ");
string cadenaAInsertar = Console.ReadLine();
Console.WriteLine("-----------------------------------------------------------");
string cadenaInsertada = cadena14.Insert(posicionInsercion, cadenaAInsertar);
Console.WriteLine($"La cadena con la inserción es: {cadenaInsertada}");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Presione una tecla para continuar...");
Console.ReadKey();
Console.Clear();
Console.WriteLine("Eliminación de subcadenas");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Presione una tecla para continuar...");
Console.ReadKey();
Console.Clear();
Console.WriteLine("Ingrese una cadena de texto: ");
string cadena15 = Console.ReadLine();
Console.WriteLine($"Cadena ingresada: {cadena15}");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Ingrese la posición de eliminación: ");
int posicionEliminacion = int.Parse(Console.ReadLine());
Console.WriteLine("Ingrese la longitud de la subcadena a eliminar: ");
int longitudEliminacion = int.Parse(Console.ReadLine());
Console.WriteLine("-----------------------------------------------------------");
string cadenaEliminada = cadena15.Remove(posicionEliminacion, longitudEliminacion);
Console.WriteLine($"La cadena con la eliminación es: {cadenaEliminada}");
Console.WriteLine("-----------------------------------------------------------");
Console.WriteLine("Presione una tecla para continuar...");
Console.ReadKey();
Console.Clear();
Console.ForegroundColor = color;

